### ISSUE TITLE
Write ADR on odh operator deployment

### ISSUE THREAD

**Issue by HumairAK** [open-services-group/devsecops#10]
We should start documenting how we're deploying the ODH operator in OSC clusters. What are the pros and cons of using OLM vs manually deploying the operator? When should one use olm over manual and vice versa?

**Comment by Gkrumbach07** [comment]
**WIP: suggestions, additions, edits welcome**

**OLM Pros**
- > allows maintainers granular authoring of the update path [[ 1 ]](https://github.com/operator-framework/operator-lifecycle-manager#over-the-air-updates-and-catalogs)

**OLM Cons**
- cluster admin access gives users the ability to create their own kfdefs, allowing them to deploy whatever they want. (security risk)


[ 1 ] - https://github.com/operator-framework/operator-lifecycle-manager#over-the-air-updates-and-catalogs

**Comment by HumairAK** [comment]
I think we could use more info for both. 

Some thoughts: 

Pros: 
- easier to install
- do not need to managed resources manually
- Easier to manage updates
- Is the currently encouraged/advertised way to install ODH, I do not think ODH even has docs/manifests on how to install the operator manually 

Cons: 
see:  
https://github.com/opendatahub-io/opendatahub-operator/issues/85
https://github.com/opendatahub-io/opendatahub-operator/issues/85
https://github.com/operate-first/apps/issues/206

We should also mention that, OLM is only recommended if users will only interact with services installed on OCP, and not ocp directly. In the latter case, we cannot recomment using OLM as it's a security risk.

**Comment by Gkrumbach07** [comment]
**WIP: suggestions, additions, edits welcome**

**OLM Pros**
- allows maintainers granular authoring of the update path 
- easier to install
- do not need to managed resources manually
- Easier to manage updates
- Is the currently encouraged/advertised way to install ODH

**OLM Cons**
- cluster admin access gives users the ability to create their own kfdefs, allowing them to deploy whatever they want. (security risk)
- ODH has cluster admin, ODH deploys kfdefs
- I can deploy a kfdef as a project admin or with an edit role
- I can point kfdef to deploy manifests from any location
- I can put a cluster rolebinding with me as a cluster admin in a repo and have a kfdef point to this repo

OLM makes managing resources and versions easier, however it exposes a security vulnerability when admin access is given. We cannot recommend OLM unless users plan to only interact with services already installed on the OCP cluster, and not OCP cluster directly.

**Comment by HumairAK** [comment]
@Gkrumbach07 Can you also apply an ADR format, and add some context, decision, etc.? here's a simple template example for an ADR: https://github.com/joelparkerhenderson/architecture-decision-record/blob/main/templates/decision-record-template-by-michael-nygard/index.md

Examples of previous ADR's from operate-first [here](https://github.com/operate-first/blueprint/tree/main/adr).

**Comment by Gkrumbach07** [comment]
# When To Use OLM

## Status

_Proposed_

## Context and Problem Statement

Open Data Hub (ODH) currently recommends to be installed using Operator Lifecycle Manager (OLM). This deployment strategy introduces a known security vulnerability for the cluster. By default all users with `admin` and `edit` access on any namespace/project can deploy a kfdef resource which effects the whole cluster. They can point kfdefs to deploy manifests from any location and then put a cluster role binding with themself as a cluster admin. 

## Decision

OLM should not be used to deploy ODH unless users plan to only interact with services already installed on the cluster, and not the cluster directly. Therefore, users cannot be given `admin` and `edit` access to their namespaces when using OLM.

## Consequences

OLM made ODH easier to install and manage, so the decision to manually install ODH will add complexity to the deployment process.

### OLM Pros

- OLM allows maintainers granular authoring of the update path.
- OLM is easier to install.
- OLM managers do not need to manage resources manually.
- OLM makes it easier to manage updates.
- OLM is the currently encouraged/advertised way to install ODH

### OLM Cons

- Cluster admin access gives users the ability to create their own kfdefs, allowing them to deploy whatever they want (security risk)
     1. ODH has cluster admin, meaning ODH deploys kfdefs.
     2. A user can deploy a kfdef as a project admin or with an edit role.
     3. A user can point kfdef to deploy manifests from any location.
     4. A user can put a cluster rolebinding with me as a cluster admin in a repo and have a kfdef point to this repo
