### ISSUE TITLE
Devsecops ODH documentation

### ISSUE THREAD

**Issue by Gregory-Pereira** [open-services-group/devsecops#14]
We are moving into the end of this quarter and would like to focus on the OKRs that WG-Devsecops is responsible for.
To that end we would like to make a point of documenting our progress up until now. Here are some things we should be documenting based on WG-Decsecops work meeting of March 16th:

- WG-Devsecops / Operate-First deployment of ODH:
    - [x] ADR comparing and contrasting OLM vs standard ODH deployment (direct operator deployment as previously used by Operate-first) (@Gkrumbach07)
    - [ ]  Gaps in various ODH deployment models (ODH /RHODS/Operate-first) (@harshad16 )
    - [ ]  Current deployment model in `operate-first/odh-manifests` (@Gregory-Pereira)
        - Branch structure, how to update version of ODH, etc.
- Knowledge gained from operating ODH in Operate-first (@4n4nd):
    - Management of ODH jupyerhub (@HumairAK expand this list):
        - [ ] Expanding Jupyterhub PVCs
        - [ ] Backing up data from PVCs
        - [ ] how to give admin/user access to openshift groups
        - [ ] how to access a user's nb using admin interface
        - [ ] using jh idle culler
        - [ ] what configmaps you should manage vs odh
        - [ ] what metrics/things to monitor if applicable
        - [ ] see jh runbook if there are any other issues, debugging steps
        - [ ] links to relevant docs
        - [ ] how to manage multiple JH in one ocp cluster (atm I don't think you can do it easily due to the traffik clusterrolebinding issue we had when we were updating from 1.1.0 to 1.1.1 on smaug)
    - Using alternate datasource management tool (cloudbeaver)
- Any missing pieces of documentation that are missing in upstream.

These should be constructed as markdown files / ADRs, and we hope to move as much as we can to [upstream](https://github.com/opendatahub-io/odh-manifests).

**Comment by Gregory-Pereira** [comment]
@harshad16 I didn't see an issue yet so I went ahead and made one.

**Comment by harshad16** [comment]
Thanks @Gregory-Pereira .
This is amazing :100:

**Comment by harshad16** [comment]
Completed with the docs link with the prs.
Thanks everyone who worked on this :100:
