### ISSUE TITLE
TAG vs BRANCHES

### ISSUE THREAD

**Issue by harshad16** [open-services-group/devsecops#18]

**Comment by Gkrumbach07** [comment]
**Branch**: contains all the commit (history is available)
**Tag**: pointer to the commit from one of branches (active or inactive) 

**Problems with using branches:** 
- Every time there is a new ODH version, we have to create a new branch and push that branch manually. If the changes are pushed to an existing branch, this could effect existing deployments .


**Problems with using tags:** 
- kfdef would need to be updated in apps repo each time a new tag is created for a cluster.
- Management of tags could be a issue.

_Tags exmaple_

v1.1.2
 - **Branch**: smaug-v1.1.2
     - commit 1
     - commit 2
 - **Tag**: smaug-v1.1.2-1
      - v1.1.2 (from upstream) + commits 1,2,3,4
 - **Tag**: smaug-v1.1.2-2
     - v1.1.2 (from upstream) + commits 1,2,3,4 + 5,6,7
    
v1.1.3

**Comment by harshad16** [comment]
This discussion would be carried on the operate-first/odh-manifests repository as per requirements.
This not critical as of the moments
Thanks for the effective discussion :100:
