### ISSUE TITLE
What cluster to deploy ODH and associated tooling on? 

### ISSUE THREAD

**Issue by HumairAK** [open-services-group/devsecops#3]
We should start discussions on what cluster we'll be targeting to deploy ODH and associated tooling on. 

Acceptance criteria: 
- [ ] A list of resource requirements. 
What resources do you we need or should be able to accomodate? What users? 

- [ ] Identify a cluster. 
Based on these requirements, is there an existing cluster we can use? Do we need to request a new one?

**Comment by HumairAK** [comment]
@durandom @goern @harshad16

**Comment by HumairAK** [comment]
@durandom @rbo I noticed that we have not much deployed on rick, but there's about ~32 cores available on workers, but OCS is also installed. My understanding is that it is recommended to have 30-40 cores reserved for OCS. So then would that mean we should not use rick for this? I imagine we'd need ~15 cores for ODH+JH+some user notebooks. 

What bout Morty cluster? That seems to have a decent chunk of resources, though most of the bigger nodes are named storage, not sure if we could use these for ODH+JH+notebooks.

**Comment by durandom** [comment]
Before proceeding, this should be discussed in a subproject of operate-first/sig-operations.
We _need_ to have an overview of the available resources and what workloads are running on them.

**Comment by HumairAK** [comment]
Decided: OSC dev cluster
