### ISSUE TITLE
Add odh configurations for osc dev cluster to odh manifests fork

### ISSUE THREAD

**Issue by HumairAK** [open-services-group/devsecops#8]
Move configs from here: https://github.com/operate-first/apps/tree/master/odh-manifests/osc

To here: https://github.com/operate-first/odh-manifests

- [x] add apps repo's odh-manifests for osc--cl2 cluster to new `odh-manifests` fork in operate-first org 
- [x] point all kfdefs deployed in `apps` repo for the [osc-cl2](https://github.com/operate-first/apps/tree/master/odh-manifests/osc) cluster to leverage the new `odh-manifests` fork 
- [x] remove old odh-manifests overrides in the `apps` repo for `osc-cl2`

**Comment by harshad16** [comment]
Thanks everyone for working on this. :100: 
The operate-first is now using the odh-manifests, the overrirde bit is being carried on the operate-first side.
